version: '3.8'

services:
  token-fetcher:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:3000
    restart: unless-stopped
